import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Simulador de Rendimento",
  description: "Generated by create next app",
  // icons: {
  //   icon: '/favicon.ico',
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full bg-white shadow p-4 flex justify-center gap-6 mb-6">
          <Link href="/" className="text-indigo-600 hover:underline text-lg font-medium">
            Simulador de Rendimento
          </Link>
          <Link href="/renda-familiar" className="text-indigo-600 hover:underline text-lg font-medium">
            Renda Familiar
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
